# @package _global_
dataset:
  dataloader_params:
    num_workers: 0
    persistent_workers: false
    batch_size: 4
    pin_memory: false
trainer:
  gpus: null
  accelerator: null
  plugins: null
  precision: 32
wandb:
  group: debug