# @package _global_
dataset:
  dataloader_params:
    num_workers: 128
    persistent_workers: false
    batch_size: 256
trainer:
  gpus: null
  accelerator: null
  plugins: null
  precision: 32
wandb:
  group: debug